<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'OnnxVision.OpenVino' Or '$(MSBuildProjectName)' == 'OnnxVision.OpenVino.Backend'">
    <BaseIntermediateOutputPath>obj\openvino\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj\openvino\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
