<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>OnnxVision.OpenVino</AssemblyName>
    <BaseOutputPath>bin\openvino\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ImageClassifier.cs" />
    <ProjectReference Include="OnnxVision.OpenVino.Backend.csproj" />
    <Reference Include="Open_eVision_NetApi_22_12">
      <HintPath>C:\VisionRef64\Open_eVision_NetApi_22_12.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
