<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ImageClassifier.cs" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.1" />
    <Reference Include="Open_eVision_NetApi_22_12">
      <HintPath>C:\VisionRef64\Open_eVision_NetApi_22_12.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
