[project]
name = "0603-seal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnx>=1.22.0",
    "onnxruntime>=1.27.0",
    "onnxruntime-gpu<1.27",
    "onnxscript>=0.5",
    "onnxslim>=0.1.94",
    "opencv-python>=4.12",
    "pillow>=11.0",
    "pyside6>=6.8",
    "rfdetr[augment,loggers,lora,onnx,train,visual]>=1.9.0",
    "timm>=1.0.19",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "triton-windows>=3.7.1.post27",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
