"""Train a small NMS-free, query-based detector with a timm backbone.

This is an experiment alongside ``train_timm_detection.py`` (the existing
RetinaNet baseline).  The task head is a fixed-size set predictor inspired by
DETR-style detectors:

* a timm ``features_only`` encoder and FPN produce multi-scale image tokens;
* learned object queries attend to those tokens with standard tensor ops;
* Hungarian one-to-one matching trains each query to represent at most one
  object; and
* inference emits one box/class score per query, so deployment does not need
  anchors, class-wise NMS, or a custom post-processing operator.

The dataset is the COCO layout produced by ``dataset_builder.py``::

    dataset/
      images/{train,val,test}/...
      annotations/instances_{train,val,test}.json

Images are stretched to a fixed square by default.  This matches the embedded
BW8/C24 preprocessing generated by the companion exporter.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
from collections import OrderedDict, defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import timm
import torch
from PIL import Image, ImageOps
from tqdm import tqdm
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision.ops import FeaturePyramidNetwork, generalized_box_iou, box_iou
from torchvision.transforms.functional import pil_to_tensor


MODEL_NAME = "mobilenetv4_conv_small.e3600_r256_in1k"
OUT_INDICES = (2, 3, 4)
DEFAULT_FPN_CHANNELS = 128
DEFAULT_NUM_QUERIES = 100
DEFAULT_AUTO_QUERY_HEADROOM = 0.25
DEFAULT_AUTO_QUERY_ROUND_TO = 8
DEFAULT_AUTO_QUERY_MINIMUM = 8
DEFAULT_DECODER_LAYERS = 2
DEFAULT_ATTENTION_HEADS = 4
DEFAULT_BBOX_LOSS_WEIGHT = 5.0
DEFAULT_GIOU_LOSS_WEIGHT = 2.0
DEFAULT_NO_OBJECT_WEIGHT = 0.1
PROGRESS_BAR_FORMAT = "{desc}: {percentage:3.0f}% {bar} {n_fmt}/{total_fmt} {rate_fmt} {elapsed}"


def set_seed(seed: int, deterministic: bool) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if deterministic:
        os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True
        torch.use_deterministic_algorithms(True)


def seed_worker(worker_id: int) -> None:
    del worker_id
    seed = torch.initial_seed() % (2**32)
    random.seed(seed)
    np.random.seed(seed)


def collate_detection_batch(batch):
    images, targets = zip(*batch)
    return list(images), list(targets)


def resolve_image_path(root: Path, split: str, file_name: str) -> Path:
    relative = Path(file_name)
    candidates = (
        root / relative,
        root / "images" / split / relative.name,
        root / relative.name,
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(
        f"COCO image {file_name!r} from {split!r} was not found below {root}; "
        f"checked: {', '.join(str(path) for path in candidates)}"
    )


class CocoDetectionDataset(Dataset):
    """Dependency-free COCO reader with normalized XYXY target boxes."""

    def __init__(
        self,
        root: Path,
        split: str,
        imgsz: int,
        train: bool,
        stretch: bool,
        max_images: int | None = None,
    ):
        self.root = root.resolve()
        self.split = split
        self.imgsz = int(imgsz)
        self.train = train
        self.stretch = stretch
        annotation_path = self.root / "annotations" / f"instances_{split}.json"
        if not annotation_path.is_file():
            raise FileNotFoundError(f"Missing COCO annotation file: {annotation_path}")
        try:
            document = json.loads(annotation_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ValueError(f"Cannot read COCO annotations {annotation_path}: {error}") from error

        categories = document.get("categories")
        if not isinstance(categories, list) or not categories:
            raise ValueError(f"COCO annotations must contain non-empty categories: {annotation_path}")
        ordered_categories = sorted(categories, key=lambda item: int(item["id"]))
        self.class_names = [str(item["name"]) for item in ordered_categories]
        self.category_to_label = {
            int(item["id"]): index for index, item in enumerate(ordered_categories)
        }

        images = document.get("images")
        if not isinstance(images, list) or not images:
            raise ValueError(f"COCO annotations must contain non-empty images: {annotation_path}")
        self.images = []
        for item in images[:max_images] if max_images is not None else images:
            image_id = int(item["id"])
            file_name = str(item["file_name"])
            path = resolve_image_path(self.root, split, file_name)
            self.images.append({"id": image_id, "path": path, "file_name": file_name})

        annotations_by_image: dict[int, list[dict[str, Any]]] = defaultdict(list)
        for annotation in document.get("annotations", []):
            annotations_by_image[int(annotation["image_id"])].append(annotation)
        self.annotations_by_image = annotations_by_image

    def max_labeled_boxes_per_image(self) -> int:
        """Return the largest valid target set in the loaded split."""
        maximum = 0
        for record in self.images:
            count = 0
            for annotation in self.annotations_by_image.get(record["id"], []):
                if int(annotation["category_id"]) not in self.category_to_label:
                    continue
                _, _, box_width, box_height = (float(value) for value in annotation["bbox"])
                if box_width > 0.0 and box_height > 0.0:
                    count += 1
            maximum = max(maximum, count)
        return maximum

    def __len__(self) -> int:
        return len(self.images)

    def __getitem__(self, index: int):
        record = self.images[index]
        with Image.open(record["path"]) as source:
            image = source.convert("RGB")
        width, height = image.size
        boxes: list[list[float]] = []
        labels: list[int] = []
        areas: list[float] = []
        for annotation in self.annotations_by_image.get(record["id"], []):
            category_id = int(annotation["category_id"])
            if category_id not in self.category_to_label:
                continue
            x, y, box_width, box_height = (float(value) for value in annotation["bbox"])
            x1 = max(0.0, min(float(width), x))
            y1 = max(0.0, min(float(height), y))
            x2 = max(0.0, min(float(width), x + box_width))
            y2 = max(0.0, min(float(height), y + box_height))
            if x2 <= x1 or y2 <= y1:
                continue
            boxes.append([x1, y1, x2, y2])
            labels.append(self.category_to_label[category_id])
            areas.append((x2 - x1) * (y2 - y1))

        boxes_tensor = torch.tensor(boxes, dtype=torch.float32).reshape(-1, 4)
        labels_tensor = torch.tensor(labels, dtype=torch.int64)
        if self.stretch:
            scale_x = self.imgsz / width
            scale_y = self.imgsz / height
            image = image.resize((self.imgsz, self.imgsz), Image.Resampling.BILINEAR)
            if boxes_tensor.numel():
                boxes_tensor *= torch.tensor([scale_x, scale_y, scale_x, scale_y])
            areas = [area * scale_x * scale_y for area in areas]
            canvas_width = canvas_height = self.imgsz
        else:
            canvas_width, canvas_height = width, height

        if self.train and random.random() < 0.5:
            image = ImageOps.mirror(image)
            if boxes_tensor.numel():
                left = boxes_tensor[:, 0].clone()
                boxes_tensor[:, 0] = image.width - boxes_tensor[:, 2]
                boxes_tensor[:, 2] = image.width - left

        if boxes_tensor.numel():
            boxes_tensor /= torch.tensor(
                [canvas_width, canvas_height, canvas_width, canvas_height], dtype=torch.float32
            )
        target = {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "image_id": torch.tensor(record["id"], dtype=torch.int64),
            "area": torch.tensor(areas, dtype=torch.float32),
            "iscrowd": torch.zeros(len(labels), dtype=torch.int64),
        }
        return pil_to_tensor(image).float().div(255.0), target


def auto_num_queries(max_labeled_boxes: int) -> int:
    """Choose a rounded query capacity with modest headroom over annotations."""
    required = max(1, int(math.ceil(max_labeled_boxes * (1.0 + DEFAULT_AUTO_QUERY_HEADROOM))))
    rounded = int(math.ceil(required / DEFAULT_AUTO_QUERY_ROUND_TO) * DEFAULT_AUTO_QUERY_ROUND_TO)
    return max(DEFAULT_AUTO_QUERY_MINIMUM, rounded)


class TimmFpnBackbone(nn.Module):
    """Use timm's multi-scale feature interface as a detector backbone."""

    def __init__(
        self,
        model_name: str,
        pretrained: bool,
        fpn_channels: int,
        out_indices: tuple[int, ...] = OUT_INDICES,
    ):
        super().__init__()
        self.encoder = timm.create_model(
            model_name,
            pretrained=pretrained,
            features_only=True,
            out_indices=out_indices,
        )
        channels = list(self.encoder.feature_info.channels())
        reductions = list(self.encoder.feature_info.reduction())
        if reductions != [8, 16, 32]:
            raise ValueError(
                f"{model_name!r} must expose stride 8/16/32 features; received reductions={reductions}"
            )
        self.fpn = FeaturePyramidNetwork(channels, out_channels=fpn_channels)
        self.out_channels = int(fpn_channels)
        self.model_name = model_name
        self.feature_channels = channels
        self.feature_reductions = reductions

    def forward(self, images: torch.Tensor) -> OrderedDict[str, torch.Tensor]:
        features = self.encoder(images)
        return self.fpn(OrderedDict((str(index), value) for index, value in enumerate(features)))


def model_data_config(backbone: TimmFpnBackbone) -> dict[str, Any]:
    config = dict(timm.data.resolve_model_data_config(backbone.encoder))
    config["mean"] = [float(value) for value in config.get("mean", (0.485, 0.456, 0.406))]
    config["std"] = [float(value) for value in config.get("std", (0.229, 0.224, 0.225))]
    config["input_size"] = [int(value) for value in config.get("input_size", (3, 224, 224))]
    config["interpolation"] = str(config.get("interpolation", "bilinear"))
    config.pop("crop_pct", None)
    config["crop_mode"] = "none"
    return config


def _mlp(input_dim: int, hidden_dim: int, output_dim: int) -> nn.Sequential:
    return nn.Sequential(nn.Linear(input_dim, hidden_dim), nn.GELU(), nn.Linear(hidden_dim, output_dim))


class NmsFreeSetDetector(nn.Module):
    """Fixed-query detector whose output is already a deduplicated set."""

    def __init__(
        self,
        backbone: TimmFpnBackbone,
        num_classes: int,
        num_queries: int,
        decoder_layers: int,
        attention_heads: int,
        image_mean: list[float],
        image_std: list[float],
        bbox_loss_weight: float,
        giou_loss_weight: float,
        no_object_weight: float,
    ):
        super().__init__()
        if backbone.out_channels % attention_heads:
            raise ValueError("--fpn-channels must be divisible by --attention-heads")
        if num_queries < 1 or decoder_layers < 1:
            raise ValueError("num_queries and decoder_layers must be positive")
        self.backbone = backbone
        self.num_classes = int(num_classes)
        self.num_queries = int(num_queries)
        self.decoder_layers = int(decoder_layers)
        self.attention_heads = int(attention_heads)
        self.d_model = int(backbone.out_channels)
        self.bbox_loss_weight = float(bbox_loss_weight)
        self.giou_loss_weight = float(giou_loss_weight)
        self.no_object_weight = float(no_object_weight)
        self.register_buffer("image_mean", torch.tensor(image_mean, dtype=torch.float32).view(1, 3, 1, 1))
        self.register_buffer("image_std", torch.tensor(image_std, dtype=torch.float32).view(1, 3, 1, 1))

        self.query_embed = nn.Embedding(self.num_queries, self.d_model)
        self.level_embed = nn.Parameter(torch.zeros(len(OUT_INDICES), self.d_model))
        self.position_proj = nn.Linear(2, self.d_model, bias=False)
        self.query_norms = nn.ModuleList(nn.LayerNorm(self.d_model) for _ in range(decoder_layers))
        self.memory_norms = nn.ModuleList(nn.LayerNorm(self.d_model) for _ in range(decoder_layers))
        self.query_projections = nn.ModuleList(
            nn.Linear(self.d_model, self.d_model, bias=False) for _ in range(decoder_layers)
        )
        self.key_projections = nn.ModuleList(
            nn.Linear(self.d_model, self.d_model, bias=False) for _ in range(decoder_layers)
        )
        self.value_projections = nn.ModuleList(
            nn.Linear(self.d_model, self.d_model, bias=False) for _ in range(decoder_layers)
        )
        self.attention_outputs = nn.ModuleList(
            nn.Linear(self.d_model, self.d_model) for _ in range(decoder_layers)
        )
        self.ffns = nn.ModuleList(
            nn.Sequential(
                nn.Linear(self.d_model, self.d_model * 2),
                nn.GELU(),
                nn.Linear(self.d_model * 2, self.d_model),
            )
            for _ in range(decoder_layers)
        )
        self.box_head = _mlp(self.d_model, self.d_model, 4)
        self.class_head = _mlp(self.d_model, self.d_model, self.num_classes + 1)

    def _memory_tokens(self, features: OrderedDict[str, torch.Tensor]) -> torch.Tensor:
        memory_parts = []
        for level, feature in enumerate(features.values()):
            _, _, height, width = feature.shape
            tokens = feature.flatten(2).transpose(1, 2)
            x = torch.arange(width, device=feature.device, dtype=feature.dtype)
            y = torch.arange(height, device=feature.device, dtype=feature.dtype)
            x = x / max(1, width - 1)
            y = y / max(1, height - 1)
            yy, xx = torch.meshgrid(y, x, indexing="ij")
            coordinates = torch.stack((xx, yy), dim=-1).reshape(1, height * width, 2)
            tokens = tokens + self.position_proj(coordinates)
            tokens = tokens + self.level_embed[level].reshape(1, 1, -1)
            memory_parts.append(tokens)
        if not memory_parts:
            raise ValueError("The timm backbone returned no feature maps")
        return torch.cat(memory_parts, dim=1)

    def forward_normalized(self, normalized_images: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        features = self.backbone(normalized_images)
        memory = self._memory_tokens(features)
        query = self.query_embed.weight.unsqueeze(0).expand(normalized_images.shape[0], -1, -1)
        scale = self.d_model ** -0.5
        for query_norm, memory_norm, q_proj, k_proj, v_proj, out_proj, ffn in zip(
            self.query_norms,
            self.memory_norms,
            self.query_projections,
            self.key_projections,
            self.value_projections,
            self.attention_outputs,
            self.ffns,
        ):
            query_input = query_norm(query)
            memory_input = memory_norm(memory)
            attention = torch.matmul(q_proj(query_input), k_proj(memory_input).transpose(1, 2)) * scale
            attention = torch.softmax(attention, dim=-1)
            query = query + out_proj(torch.matmul(attention, v_proj(memory_input)))
            query = query + ffn(query_norm(query))

        class_logits = self.class_head(query)
        center_size = self.box_head(query).sigmoid()
        centers = center_size[..., :2]
        sizes = center_size[..., 2:]
        boxes = torch.cat((centers - 0.5 * sizes, centers + 0.5 * sizes), dim=-1).clamp(0.0, 1.0)
        return class_logits, boxes

    def forward(self, images: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        normalized = (images - self.image_mean) / self.image_std
        return self.forward_normalized(normalized)

    def export_outputs(self, normalized_images: torch.Tensor):
        class_logits, boxes = self.forward_normalized(normalized_images)
        probabilities = torch.softmax(class_logits, dim=-1)[..., : self.num_classes]
        scores, class_ids = probabilities.max(dim=-1)
        return boxes, scores, class_ids.to(torch.int64)

    def loss(self, class_logits: torch.Tensor, boxes: torch.Tensor, targets: list[dict[str, torch.Tensor]]):
        batch_size = class_logits.shape[0]
        no_object = torch.full(
            (batch_size, self.num_queries),
            self.num_classes,
            dtype=torch.int64,
            device=class_logits.device,
        )
        matched_predictions: list[tuple[torch.Tensor, torch.Tensor]] = []
        matched_count = 0
        for batch_index, target in enumerate(targets):
            target_boxes = target["boxes"].to(class_logits.device)
            target_labels = target["labels"].to(class_logits.device)
            if target_boxes.numel() == 0:
                matched_predictions.append((torch.empty(0, dtype=torch.int64, device=boxes.device), target_boxes))
                continue
            with torch.no_grad():
                probabilities = class_logits[batch_index].float().softmax(dim=-1)[:, : self.num_classes]
                cost_class = -probabilities[:, target_labels]
                cost_bbox = torch.cdist(boxes[batch_index].float(), target_boxes.float(), p=1)
                cost_giou = -generalized_box_iou(boxes[batch_index].float(), target_boxes.float())
                total_cost = (
                    cost_class
                    + self.bbox_loss_weight * cost_bbox
                    + self.giou_loss_weight * cost_giou
                )
                prediction_indices, target_indices = hungarian_assignment(total_cost)
            prediction_indices = torch.as_tensor(prediction_indices, dtype=torch.int64, device=boxes.device)
            target_indices = torch.as_tensor(target_indices, dtype=torch.int64, device=boxes.device)
            if prediction_indices.numel():
                no_object[batch_index, prediction_indices] = target_labels[target_indices]
                matched_predictions.append((
                    boxes[batch_index, prediction_indices],
                    target_boxes[target_indices],
                ))
                matched_count += int(prediction_indices.numel())
            else:
                matched_predictions.append((torch.empty(0, 4, device=boxes.device), target_boxes[:0]))
        weights = torch.ones(self.num_classes + 1, device=class_logits.device, dtype=class_logits.dtype)
        weights[-1] = self.no_object_weight
        loss_class = nn.functional.cross_entropy(class_logits.transpose(1, 2), no_object, weight=weights)
        if matched_count:
            predicted_boxes = torch.cat([item[0] for item in matched_predictions if item[0].numel()], dim=0)
            target_boxes = torch.cat([item[1] for item in matched_predictions if item[1].numel()], dim=0)
            loss_bbox = nn.functional.l1_loss(predicted_boxes, target_boxes, reduction="sum") / matched_count
            loss_giou = (1.0 - generalized_box_iou(predicted_boxes, target_boxes).diag()).sum() / matched_count
        else:
            loss_bbox = boxes.sum() * 0.0
            loss_giou = boxes.sum() * 0.0
        return {
            "loss_class": loss_class,
            "loss_bbox": self.bbox_loss_weight * loss_bbox,
            "loss_giou": self.giou_loss_weight * loss_giou,
            "loss_total": loss_class + self.bbox_loss_weight * loss_bbox + self.giou_loss_weight * loss_giou,
        }


def hungarian_assignment(cost: torch.Tensor) -> tuple[list[int], list[int]]:
    """Return a minimum-cost rectangular assignment without a SciPy dependency."""
    matrix = cost.detach().cpu().numpy().astype(np.float64, copy=False)
    if matrix.ndim != 2 or matrix.shape[1] == 0:
        return [], []
    transposed = matrix.shape[0] > matrix.shape[1]
    if transposed:
        matrix = matrix.T
    rows, columns = matrix.shape
    u = [0.0] * (rows + 1)
    v = [0.0] * (columns + 1)
    p = [0] * (columns + 1)
    way = [0] * (columns + 1)
    for row in range(1, rows + 1):
        p[0] = row
        column_0 = 0
        minimum = [float("inf")] * (columns + 1)
        used = [False] * (columns + 1)
        while True:
            used[column_0] = True
            row_0 = p[column_0]
            delta = float("inf")
            column_1 = 0
            for column in range(1, columns + 1):
                if not used[column]:
                    current = matrix[row_0 - 1, column - 1] - u[row_0] - v[column]
                    if current < minimum[column]:
                        minimum[column] = current
                        way[column] = column_0
                    if minimum[column] < delta:
                        delta = minimum[column]
                        column_1 = column
            for column in range(columns + 1):
                if used[column]:
                    u[p[column]] += delta
                    v[column] -= delta
                else:
                    minimum[column] -= delta
            column_0 = column_1
            if p[column_0] == 0:
                break
        while True:
            column_1 = way[column_0]
            p[column_0] = p[column_1]
            column_0 = column_1
            if column_0 == 0:
                break
    pairs = [(p[column] - 1, column - 1) for column in range(1, columns + 1) if p[column]]
    if transposed:
        return [column for row, column in pairs], [row for row, column in pairs]
    return [row for row, column in pairs], [column for row, column in pairs]


def build_detector(
    model_name: str,
    num_classes: int,
    fpn_channels: int,
    num_queries: int,
    decoder_layers: int,
    attention_heads: int,
    pretrained: bool = True,
    image_mean: list[float] | None = None,
    image_std: list[float] | None = None,
    bbox_loss_weight: float = DEFAULT_BBOX_LOSS_WEIGHT,
    giou_loss_weight: float = DEFAULT_GIOU_LOSS_WEIGHT,
    no_object_weight: float = DEFAULT_NO_OBJECT_WEIGHT,
) -> tuple[NmsFreeSetDetector, TimmFpnBackbone, dict[str, Any]]:
    backbone = TimmFpnBackbone(model_name, pretrained, fpn_channels)
    config = model_data_config(backbone)
    mean = image_mean or config["mean"]
    std = image_std or config["std"]
    model = NmsFreeSetDetector(
        backbone,
        num_classes,
        num_queries,
        decoder_layers,
        attention_heads,
        mean,
        std,
        bbox_loss_weight,
        giou_loss_weight,
        no_object_weight,
    )
    config.update({"mean": mean, "std": std})
    return model, backbone, config


def decode_predictions(
    class_logits: torch.Tensor,
    boxes: torch.Tensor,
    class_names: list[str],
    score_threshold: float,
) -> list[dict[str, torch.Tensor]]:
    probabilities = torch.softmax(class_logits, dim=-1)[..., : len(class_names)]
    scores, labels = probabilities.max(dim=-1)
    predictions = []
    for batch_index in range(class_logits.shape[0]):
        keep = scores[batch_index] >= score_threshold
        predictions.append({
            "boxes": boxes[batch_index, keep],
            "scores": scores[batch_index, keep],
            "labels": labels[batch_index, keep],
        })
    return predictions


def average_precision(scores_and_matches: list[tuple[float, bool]], ground_truth_count: int) -> float:
    if ground_truth_count <= 0:
        return float("nan")
    if not scores_and_matches:
        return 0.0
    ordered = sorted(scores_and_matches, key=lambda item: item[0], reverse=True)
    true_positive = np.cumsum([int(item[1]) for item in ordered], dtype=np.float64)
    false_positive = np.cumsum([int(not item[1]) for item in ordered], dtype=np.float64)
    recall = true_positive / max(1, ground_truth_count)
    precision = true_positive / np.maximum(1.0, true_positive + false_positive)
    precision_envelope = np.maximum.accumulate(precision[::-1])[::-1]
    recall_points = np.concatenate(([0.0], recall))
    precision_points = np.concatenate(([precision_envelope[0]], precision_envelope))
    return float(np.sum((recall_points[1:] - recall_points[:-1]) * precision_points[1:]))


def detection_metrics_at_iou(
    predictions: list[dict[str, torch.Tensor]],
    targets: list[dict[str, torch.Tensor]],
    class_names: list[str],
    score_threshold: float,
    iou_threshold: float = 0.5,
) -> dict[str, Any]:
    matched_detections: list[list[tuple[float, bool]]] = [[] for _ in class_names]
    ground_truth_counts = [0 for _ in class_names]
    true_positive = false_positive = false_negative = 0
    for prediction, target in zip(predictions, targets):
        predicted_boxes = prediction["boxes"].detach().cpu()
        predicted_scores = prediction["scores"].detach().cpu()
        predicted_labels = prediction["labels"].detach().cpu()
        target_boxes = target["boxes"].detach().cpu()
        target_labels = target["labels"].detach().cpu()
        for class_id in range(len(class_names)):
            gt_indices = torch.where(target_labels == class_id)[0]
            ground_truth_counts[class_id] += int(gt_indices.numel())
            prediction_indices = torch.where(
                (predicted_labels == class_id) & (predicted_scores >= score_threshold)
            )[0]
            if prediction_indices.numel():
                prediction_indices = prediction_indices[
                    torch.argsort(predicted_scores[prediction_indices], descending=True)
                ]
            used = torch.zeros(gt_indices.numel(), dtype=torch.bool)
            for prediction_index in prediction_indices.tolist():
                score = float(predicted_scores[prediction_index])
                if not gt_indices.numel():
                    matched = False
                else:
                    overlaps = box_iou(
                        predicted_boxes[prediction_index : prediction_index + 1],
                        target_boxes[gt_indices],
                    )[0]
                    overlaps[used] = -1.0
                    best_overlap, best_index = overlaps.max(dim=0)
                    matched = bool(best_overlap >= iou_threshold)
                    if matched:
                        used[best_index] = True
                matched_detections[class_id].append((score, matched))
                true_positive += int(matched)
                false_positive += int(not matched)
            false_negative += int((~used).sum())

    aps = [average_precision(items, count) for items, count in zip(matched_detections, ground_truth_counts)]
    valid_aps = [value for value in aps if math.isfinite(value)]
    precision = true_positive / max(1, true_positive + false_positive)
    recall = true_positive / max(1, true_positive + false_negative)
    return {
        "map50": float(np.mean(valid_aps)) if valid_aps else 0.0,
        "precision50": precision,
        "recall50": recall,
        "f1_50": 2 * precision * recall / max(1e-12, precision + recall),
        "per_class_ap50": {
            name: (None if not math.isfinite(ap) else float(ap))
            for name, ap in zip(class_names, aps)
        },
        "ground_truth_boxes": sum(ground_truth_counts),
        "predicted_true_positive": true_positive,
        "predicted_false_positive": false_positive,
        "missed_ground_truth": false_negative,
    }


def detection_metrics(
    predictions: list[dict[str, torch.Tensor]],
    targets: list[dict[str, torch.Tensor]],
    class_names: list[str],
    score_threshold: float,
    iou_threshold: float = 0.5,
) -> dict[str, Any]:
    """Calculate AP50, COCO-style mAP50-95, and the threshold-50 counts."""
    thresholds = tuple(round(0.50 + 0.05 * index, 2) for index in range(10))
    threshold_metrics = [
        detection_metrics_at_iou(predictions, targets, class_names, score_threshold, threshold)
        for threshold in thresholds
    ]
    metrics = (
        dict(threshold_metrics[0])
        if math.isclose(iou_threshold, thresholds[0])
        else detection_metrics_at_iou(
            predictions,
            targets,
            class_names,
            score_threshold,
            iou_threshold,
        )
    )
    metrics["map50_95"] = float(np.mean([item["map50"] for item in threshold_metrics]))
    return metrics


def move_targets(targets: list[dict[str, torch.Tensor]], device: torch.device):
    return [{key: value.to(device) for key, value in target.items()} for target in targets]


def amp_context(device: torch.device, enabled: bool, dtype: torch.dtype):
    return torch.autocast(device_type=device.type, dtype=dtype, enabled=enabled)


def peak_gpu_memory(device: torch.device) -> str:
    if device.type != "cuda":
        return "0G"
    return f"{torch.cuda.max_memory_reserved(device) / (1024 ** 3):.2f}G"


def train_progress_description(
    epoch: int,
    total_epochs: int,
    losses: dict[str, float],
    instances: int,
    imgsz: int,
    gpu_memory: str,
) -> str:
    return (
        f"{epoch:7d}/{total_epochs:<3d} {gpu_memory:>9} "
        f"{losses['loss_bbox']:10.4f} {losses['loss_class']:10.4f} "
        f"{losses['loss_giou']:10.4f} {instances:10d} {imgsz:10d}"
    )


def format_metric(value: Any) -> str:
    if value is None or not math.isfinite(float(value)):
        return "nan"
    return f"{float(value):.4f}".rstrip("0").rstrip(".")


def print_validation_summary(metrics: dict[str, Any], image_count: int) -> None:
    print(
        f"{'all':>23} {image_count:>10} {int(metrics['ground_truth_boxes']):>11} "
        f"{format_metric(metrics['precision50']):>10} {format_metric(metrics['recall50']):>10} "
        f"{format_metric(metrics['map50']):>10} {format_metric(metrics['map50_95']):>12}"
    )


def make_progress(total: int, description: str):
    return tqdm(
        total=total,
        desc=description,
        unit="it",
        dynamic_ncols=True,
        bar_format=PROGRESS_BAR_FORMAT,
    )


def train_epoch(
    model: NmsFreeSetDetector,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    scaler: torch.amp.GradScaler,
    device: torch.device,
    amp_enabled: bool,
    amp_dtype: torch.dtype,
    progress: Any | None = None,
    epoch: int = 0,
    total_epochs: int = 0,
    imgsz: int = 0,
) -> dict[str, float]:
    model.train()
    totals: defaultdict[str, float] = defaultdict(float)
    batches = 0
    for images, targets in loader:
        images = torch.stack([image.to(device, non_blocking=True) for image in images])
        targets = move_targets(targets, device)
        optimizer.zero_grad(set_to_none=True)
        with amp_context(device, amp_enabled, amp_dtype):
            class_logits, boxes = model(images)
            losses = model.loss(class_logits, boxes, targets)
        loss = losses["loss_total"]
        if not torch.isfinite(loss):
            raise FloatingPointError(f"Non-finite detection loss: {float(loss.detach().cpu())}")
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=10.0)
        scaler.step(optimizer)
        scaler.update()
        for name, value in losses.items():
            totals[name] += float(value.detach().cpu())
        batches += 1
        if progress is not None:
            averages = {name: value / batches for name, value in totals.items()}
            progress.set_description(
                train_progress_description(
                    epoch,
                    total_epochs,
                    averages,
                    sum(int(target["boxes"].shape[0]) for target in targets),
                    imgsz,
                    peak_gpu_memory(device),
                )
            )
            progress.update(1)
    return {name: value / max(1, batches) for name, value in totals.items()}


@torch.no_grad()
def evaluate(
    model: NmsFreeSetDetector,
    loader: DataLoader,
    class_names: list[str],
    device: torch.device,
    score_threshold: float,
    progress: Any | None = None,
) -> dict[str, Any]:
    model.eval()
    predictions = []
    targets = []
    for images, batch_targets in loader:
        device_images = torch.stack([image.to(device, non_blocking=True) for image in images])
        class_logits, boxes = model(device_images)
        predictions.extend(decode_predictions(class_logits, boxes, class_names, score_threshold))
        targets.extend(batch_targets)
        if progress is not None:
            progress.update(1)
    return detection_metrics(predictions, targets, class_names, score_threshold)


def save_checkpoint(
    path: Path,
    model: NmsFreeSetDetector,
    optimizer: torch.optim.Optimizer,
    epoch: int,
    classes: list[str],
    model_name: str,
    config: dict[str, Any],
    model_config: dict[str, Any],
    metrics: dict[str, Any],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "task": "object_detection",
            "architecture": "nms_free_query",
            "model_name": model_name,
            "classes": classes,
            "class_to_idx": {name: index for index, name in enumerate(classes)},
            "model_config": model_config,
            "data_config": config,
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "metrics": metrics,
            "torch_version": torch.__version__,
            "timm_version": getattr(timm, "__version__", "unknown"),
        },
        path,
    )


def make_loader(dataset: Dataset, batch: int, workers: int, pin_memory: bool, seed: int, shuffle: bool):
    kwargs: dict[str, Any] = {
        "batch_size": batch,
        "shuffle": shuffle,
        "num_workers": workers,
        "pin_memory": pin_memory,
        "persistent_workers": workers > 0,
        "collate_fn": collate_detection_batch,
        "generator": torch.Generator().manual_seed(seed),
        "worker_init_fn": seed_worker,
    }
    if workers > 0:
        kwargs["prefetch_factor"] = 2
    return DataLoader(dataset, **kwargs)


def resolve_device(requested: str) -> torch.device:
    if requested == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device(requested)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError(f"CUDA requested ({requested}) but CUDA is unavailable")
    if device.type not in {"cpu", "cuda"}:
        raise ValueError(f"Unsupported device: {requested!r}")
    return device


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", required=True, type=Path, help="COCO dataset root")
    parser.add_argument("--model", default=MODEL_NAME, help="timm backbone model name")
    parser.add_argument("--imgsz", type=int, default=384, help="Fixed square input size")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--workers", type=int, default=-1)
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument("--min-epochs", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--output", type=Path, default=Path("python-scripts/timm/runs/mobilenetv4-nms-free-query"))
    parser.add_argument("--pretrained", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--amp", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--amp-dtype", choices=("float16", "bfloat16"), default="float16")
    parser.add_argument("--deterministic", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--stretch-to-input-size", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--fpn-channels", type=int, default=DEFAULT_FPN_CHANNELS)
    parser.add_argument(
        "--num-queries",
        type=int,
        default=None,
        help=(
            "Query slots; when omitted, auto-select from the largest loaded annotation set "
            f"with {DEFAULT_AUTO_QUERY_HEADROOM:.0f}%% headroom, rounded to {DEFAULT_AUTO_QUERY_ROUND_TO}"
        ),
    )
    parser.add_argument("--decoder-layers", type=int, default=DEFAULT_DECODER_LAYERS)
    parser.add_argument("--attention-heads", type=int, default=DEFAULT_ATTENTION_HEADS)
    parser.add_argument("--bbox-loss-weight", type=float, default=DEFAULT_BBOX_LOSS_WEIGHT)
    parser.add_argument("--giou-loss-weight", type=float, default=DEFAULT_GIOU_LOSS_WEIGHT)
    parser.add_argument("--no-object-weight", type=float, default=DEFAULT_NO_OBJECT_WEIGHT)
    parser.add_argument("--score-threshold", type=float, default=0.25)
    parser.add_argument("--max-train-images", type=int)
    parser.add_argument("--max-val-images", type=int)
    parser.add_argument("--max-test-images", type=int)
    parser.add_argument("--run-test", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.imgsz < 32 or args.imgsz % 32:
        raise ValueError("--imgsz must be at least 32 and divisible by 32")
    if args.batch < 1 or args.epochs < 1 or args.patience < 0 or args.min_epochs < 0:
        raise ValueError("--batch/--epochs must be positive and --patience/--min-epochs cannot be negative")
    if args.fpn_channels < 8 or (args.num_queries is not None and args.num_queries < 1) \
            or args.decoder_layers < 1 or args.attention_heads < 1:
        raise ValueError("head dimensions must be positive")
    if not 0 <= args.score_threshold <= 1:
        raise ValueError("--score-threshold must be between 0 and 1")
    if args.fpn_channels % args.attention_heads:
        raise ValueError("--fpn-channels must be divisible by --attention-heads")

    set_seed(args.seed, args.deterministic)
    device = resolve_device(args.device)
    workers = args.workers
    if workers == -1:
        workers = min(8, max(1, (os.cpu_count() or 1) // 2)) if device.type == "cuda" else 0
    amp_enabled = bool(args.amp and device.type == "cuda")
    amp_dtype = torch.float16 if args.amp_dtype == "float16" else torch.bfloat16
    pin_memory = device.type == "cuda"

    data = args.data.expanduser().resolve()
    output = args.output.expanduser().resolve()
    train_set = CocoDetectionDataset(data, "train", args.imgsz, True, args.stretch_to_input_size, args.max_train_images)
    val_set = CocoDetectionDataset(data, "val", args.imgsz, False, args.stretch_to_input_size, args.max_val_images)
    if train_set.class_names != val_set.class_names:
        raise ValueError(f"Train/val categories differ: {train_set.class_names} != {val_set.class_names}")
    test_set = None
    if args.run_test and (data / "annotations" / "instances_test.json").is_file():
        test_set = CocoDetectionDataset(data, "test", args.imgsz, False, args.stretch_to_input_size, args.max_test_images)
        if train_set.class_names != test_set.class_names:
            raise ValueError(f"Train/test categories differ: {train_set.class_names} != {test_set.class_names}")

    split_maxima = {
        "train": train_set.max_labeled_boxes_per_image(),
        "val": val_set.max_labeled_boxes_per_image(),
    }
    if test_set is not None:
        split_maxima["test"] = test_set.max_labeled_boxes_per_image()
    max_labeled_boxes = max(split_maxima.values(), default=0)
    requested_num_queries = args.num_queries
    if requested_num_queries is None:
        args.num_queries = auto_num_queries(max_labeled_boxes)
        query_selection = "auto"
    else:
        if requested_num_queries < max_labeled_boxes:
            raise ValueError(
                f"--num-queries={requested_num_queries} is smaller than the largest loaded target set "
                f"({max_labeled_boxes} boxes); increase it or omit the flag for automatic sizing"
            )
        query_selection = "explicit"
    print(
        f"query_capacity={args.num_queries}; query_selection={query_selection}; "
        f"max_labeled_boxes={max_labeled_boxes}; split_maxima={split_maxima}"
    )

    model, backbone, data_config = build_detector(
        args.model,
        len(train_set.class_names),
        args.fpn_channels,
        args.num_queries,
        args.decoder_layers,
        args.attention_heads,
        pretrained=args.pretrained,
        bbox_loss_weight=args.bbox_loss_weight,
        giou_loss_weight=args.giou_loss_weight,
        no_object_weight=args.no_object_weight,
    )
    data_config = dict(data_config)
    data_config.update({
        "input_size": [3, args.imgsz, args.imgsz],
        "interpolation": "bilinear",
        "resize_mode": "stretch_to_input_size" if args.stretch_to_input_size else "native",
        "stretch_to_input_size": bool(args.stretch_to_input_size),
    })
    model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    scaler = torch.amp.GradScaler("cuda", enabled=amp_enabled)
    train_loader = make_loader(train_set, args.batch, workers, pin_memory, args.seed, True)
    val_loader = make_loader(val_set, args.batch, workers, pin_memory, args.seed + 1, False)

    model_config = {
        "architecture": "nms_free_query",
        "nms_required": False,
        "model_name": args.model,
        "out_indices": list(OUT_INDICES),
        "fpn_channels": args.fpn_channels,
        "num_queries": args.num_queries,
        "num_queries_selection": query_selection,
        "max_labeled_boxes": max_labeled_boxes,
        "auto_query_headroom": DEFAULT_AUTO_QUERY_HEADROOM,
        "auto_query_round_to": DEFAULT_AUTO_QUERY_ROUND_TO,
        "decoder_layers": args.decoder_layers,
        "attention_heads": args.attention_heads,
        "bbox_loss_weight": args.bbox_loss_weight,
        "giou_loss_weight": args.giou_loss_weight,
        "no_object_weight": args.no_object_weight,
        "imgsz": args.imgsz,
        "stretch_to_input_size": args.stretch_to_input_size,
        "feature_channels": backbone.feature_channels,
        "feature_reductions": backbone.feature_reductions,
    }
    parameters = {
        "epochs": args.epochs,
        "batch": args.batch,
        "lr": args.lr,
        "weight_decay": args.weight_decay,
        "workers": workers,
        "amp": amp_enabled,
        "amp_dtype": args.amp_dtype if amp_enabled else None,
        "device": str(device),
        "seed": args.seed,
        "deterministic": args.deterministic,
        "pretrained": args.pretrained,
        "num_queries_requested": requested_num_queries,
        "score_threshold": args.score_threshold,
        "max_train_images": args.max_train_images,
        "max_val_images": args.max_val_images,
        "max_test_images": args.max_test_images,
    }
    output.mkdir(parents=True, exist_ok=True)
    (output / "config.json").write_text(
        json.dumps({"model_config": model_config, "data_config": data_config, "parameters": parameters}, indent=2),
        encoding="utf-8",
    )

    best_score = -1.0
    epochs_without_improvement = 0
    history: list[dict[str, Any]] = []
    print(
        f"training nms_free_query; backbone={args.model}; classes={train_set.class_names}; "
        f"images={len(train_set)}/{len(val_set)}; queries={args.num_queries}; device={device}; imgsz={args.imgsz}; "
        "nms_required=false"
    )
    for epoch in range(1, args.epochs + 1):
        if device.type == "cuda":
            torch.cuda.reset_peak_memory_stats(device)
        print("\n      Epoch    GPU_mem   box_loss   cls_loss  giou_loss  Instances       Size")
        train_progress = make_progress(len(train_loader), f"{epoch:7d}/{args.epochs:<3d}")
        try:
            train_losses = train_epoch(
                model,
                train_loader,
                optimizer,
                scaler,
                device,
                amp_enabled,
                amp_dtype,
                progress=train_progress,
                epoch=epoch,
                total_epochs=args.epochs,
                imgsz=args.imgsz,
            )
        finally:
            train_progress.close()

        validation_description = (
            "                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95"
        )
        val_progress = make_progress(len(val_loader), validation_description)
        try:
            metrics = evaluate(
                model,
                val_loader,
                train_set.class_names,
                device,
                args.score_threshold,
                progress=val_progress,
            )
        finally:
            val_progress.close()
        print_validation_summary(metrics, len(val_set))
        scheduler.step()
        row = {"epoch": epoch, **train_losses, **metrics, "lr": optimizer.param_groups[0]["lr"]}
        history.append(row)
        print(
            f"epoch={epoch:03d} loss={train_losses['loss_total']:.5f} "
            f"class={train_losses['loss_class']:.5f} bbox={train_losses['loss_bbox']:.5f} "
            f"giou={train_losses['loss_giou']:.5f} map50={metrics['map50']:.5f} "
            f"map50_95={metrics['map50_95']:.5f} precision50={metrics['precision50']:.5f} "
            f"recall50={metrics['recall50']:.5f}"
        )
        score = float(metrics["map50"])
        if score > best_score + 1e-8:
            best_score = score
            epochs_without_improvement = 0
            save_checkpoint(output / "best.pt", model, optimizer, epoch, train_set.class_names, args.model, data_config, model_config, metrics)
        else:
            epochs_without_improvement += 1
        save_checkpoint(output / "last.pt", model, optimizer, epoch, train_set.class_names, args.model, data_config, model_config, metrics)
        if args.patience and epoch >= args.min_epochs and epochs_without_improvement >= args.patience:
            print(f"early_stop=patience({args.patience})")
            break

    with (output / "history.csv").open("w", newline="", encoding="utf-8") as handle:
        if history:
            fieldnames = sorted({key for row in history for key in row if not isinstance(row[key], dict)})
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows({key: value for key, value in row.items() if key in fieldnames} for row in history)

    best = torch.load(output / "best.pt", map_location=device, weights_only=False)
    model.load_state_dict(best["model_state_dict"])
    best_metrics = evaluate(model, val_loader, train_set.class_names, device, args.score_threshold)
    print(
        f"best_epoch={best['epoch']} best_map50={best_metrics['map50']:.5f} "
        f"best_map50_95={best_metrics['map50_95']:.5f}"
    )
    if test_set is not None:
        test_loader = make_loader(test_set, args.batch, 0, pin_memory, args.seed + 2, False)
        test_metrics = evaluate(model, test_loader, train_set.class_names, device, args.score_threshold)
        print(
            f"test_map50={test_metrics['map50']:.5f} test_precision50={test_metrics['precision50']:.5f} "
            f"test_recall50={test_metrics['recall50']:.5f} test_map50_95={test_metrics['map50_95']:.5f}"
        )
        (output / "test_metrics.json").write_text(json.dumps(test_metrics, indent=2), encoding="utf-8")

    metadata = {
        "task": "object_detection",
        "architecture": "nms_free_query",
        "nms_required": False,
        "model_name": args.model,
        "classes": train_set.class_names,
        "model_config": model_config,
        "data_config": data_config,
        "training_result": {"best_epoch": int(best["epoch"]), "best_val_metrics": best_metrics},
    }
    (output / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
